[project]
name = "kf-analysis"
version = "2.5.1"
requires-python = ">=3.12"
description = "绯月论坛活跃度数据获取与分析工具，提供论坛操作接口"
dependencies = [
    "requests",
    "beautifulsoup4",
    "lxml",
    "matplotlib",
    "numpy",
    "Pillow",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
